version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  etl:
    build: ./etl
    container_name: etl
    depends_on:
      - mongo

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
    depends_on:
      - mongo

  api:
    build: ./api
    container_name: mongo-api
    ports:
      - "5000:5000"
    depends_on:
      - mongo

volumes:
  mongo_data:
  grafana_data:

